table 'CCAA Diccionario'
	lineageTag: 9b7686f2-f191-4cac-aec5-3f9f2a6383f5

	column 'Código '
		dataType: int64
		formatString: 0
		lineageTag: fb371284-b702-4605-bb89-eea9fd1f61dd
		summarizeBy: none
		sourceColumn: "Código "

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: 872687b5-f37f-4734-adfd-9c14227b8380
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	partition 'CCAA Diccionario' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("TZDLTsMwEEV/xfI6SIQ3S4ooQkpQ1QWbKItLbBVXroP8QPBRXSA+IT/GjJ1WXc65Hvsed52sZSUfnIJNw7SH7KtOXjDy2Ex/Ls+XPIeYvEGoxMobN5hPqFEonfMryhewGp7iF2t1yPia8CMceC2DmwIi3gllcptJiMZaiB/R6MOTd6fBmWggWrjho2zd5zBS5em3kPqc0bhLzkRE8UZlqCO9XVJ2fPqOXu+gkp8hWz7DmmHuUrNmC+WNqkS5S0EdHGuWbJOn05VY642hpseMTV/xBe9xurocPezxENuvMO0D1QvDWCB/wNqMW9pr5hpZXac4jyzbassfIfv+Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Código " = _t, Descripción = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Código ", Int64.Type}, {"Descripción", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

