table 'Clase Social por Ocupación'
	lineageTag: a3b56872-d54f-47a4-894b-cef6c1fc5ee7

	column 'Código '
		dataType: int64
		formatString: 0
		lineageTag: 24b896b6-ede5-4704-ac53-62ea8d0cab8e
		summarizeBy: sum
		sourceColumn: "Código "

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: 57663a83-cab9-4586-9097-4dd8fd30c794
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	partition 'Clase Social por Ocupación' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("nZE5bgMxDEWvQkztLM4GpHedFEk3cEFLdMBAEgUtBnyclDmHLxaOPLAnA1duBIn6/P9R6vtu2S26FScyRRLlO8ywhy9KFAplsASUC24cGfasNWm15T0I+MNPBszoMDFaGVtjki1lloBO+0tCy6ad/OCoejEnNYLT1bGhoMVSk55q4B2lzGVwzd160XcPVxBq2gl1yghXQFqOTvxFPvWSko7C/6YajVH2AuXwawIbuYUVRUmFlXbow3HbRnzUEd9NjThgaDcrRvJkjxEKuMFvBRrHVxswVVFxCI2MzeNJPT5qpLTjfH6oeS8FkEnQSKcXpqLjrW7tyPSsfp+z7rPoOLMlB7l9jJKw1zeR6ZPMwzN5vpl5tKyXC1lB5nFN+qrSN72S4fuLjr7+Aw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Código " = _t, Descripción = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Código ", Int64.Type}, {"Descripción", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

