table 'Frecuencia Activ Fisica'
	lineageTag: 77360fdb-279b-4ebb-baa2-882f19317e86

	column 'Código '
		dataType: string
		lineageTag: a4bb6bbf-a047-4954-a328-c2338e584645
		summarizeBy: none
		sourceColumn: "Código "

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: bcff2c03-7d63-4d08-8d16-608e592ac0f8
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	partition 'Frecuencia Activ Fisica' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZZBNbgIxDEav8ilrVAnoFSp1xQVGLIzHUCMnHiWZuRWn4GL1QH+kdhXH0nv+7GFI27RJB8cHXRxylcrK6i94M3SVPDlMT1VgDuc5vqPg7DUTmJqCPU8mnbKULmgyxktVKR03Q9qF+n31kl3mQiDuuuhII873W1MmrLrJa7SjXoVeyB7s/of9By3rgIZFWFqokaU9kNdvJDJUKZQ1it8JscCXwv8oYBTRM5Vn7DKbPY/CHlu1Hu3jJw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Código " = _t, Descripción = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Código ", Int64.Type}, {"Descripción", type text}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Changed Type", {{"Código ", type text}}, "en-US")
				in
				    #"Changed Type with Locale"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

